import { Character, GachaCard, ShopPackage, ChatMessage } from './types';

// Mensagens de chat para os capítulos
const createChatMessages = (characterName: string, chapterNumber: number): ChatMessage[] => {
  const messages: ChatMessage[] = [
    {
      id: `msg-${chapterNumber}-1`,
      type: 'character',
      content: `Olá... finalmente você veio me ver. 😊`,
    },
    {
      id: `msg-${chapterNumber}-2`,
      type: 'character',
      content: `Estava esperando por você há tanto tempo...`,
    },
    {
      id: `msg-${chapterNumber}-3`,
      type: 'choice',
      choices: [
        { id: 'choice-1', text: 'Responder de forma gentil', nextMessageId: `msg-${chapterNumber}-4a` },
        { id: 'choice-2', text: 'Responder de forma ousada', nextMessageId: `msg-${chapterNumber}-4b` },
        { id: 'choice-3', text: 'Responder de forma misteriosa', nextMessageId: `msg-${chapterNumber}-4c` },
      ]
    },
    {
      id: `msg-${chapterNumber}-4a`,
      type: 'character',
      content: `Que doce... você sempre sabe como me fazer sorrir. ❤️`,
    },
    {
      id: `msg-${chapterNumber}-4b`,
      type: 'character',
      content: `Uau... gostei dessa sua confiança. Me deixou curiosa... 😏`,
    },
    {
      id: `msg-${chapterNumber}-4c`,
      type: 'character',
      content: `Hmm... interessante. Você é cheio de surpresas, não é? 🤔`,
    },
    {
      id: `msg-${chapterNumber}-5`,
      type: 'character',
      content: `Sabe... tenho algo especial para te mostrar...`,
    },
    {
      id: `msg-${chapterNumber}-6`,
      type: 'character',
      content: `Mas antes, me diz uma coisa...`,
    },
    {
      id: `msg-${chapterNumber}-7`,
      type: 'choice',
      choices: [
        { id: 'choice-4', text: 'O que você quer saber?', nextMessageId: `msg-${chapterNumber}-8a` },
        { id: 'choice-5', text: 'Estou curioso...', nextMessageId: `msg-${chapterNumber}-8b` },
        { id: 'choice-6', text: 'Pode perguntar', nextMessageId: `msg-${chapterNumber}-8c` },
      ]
    },
    {
      id: `msg-${chapterNumber}-8a`,
      type: 'character',
      content: `Você está gostando de passar esse tempo comigo? 💕`,
    },
    {
      id: `msg-${chapterNumber}-8b`,
      type: 'character',
      content: `Hehe... adoro quando você fica assim. Vou te mostrar agora... 😘`,
    },
    {
      id: `msg-${chapterNumber}-8c`,
      type: 'character',
      content: `Tão educado... isso me agrada. Olha só isso... ✨`,
    },
    {
      id: `msg-${chapterNumber}-9`,
      type: 'character',
      content: `Deixa eu te mostrar algo especial...`,
      imageUnlock: true,
    },
    {
      id: `msg-${chapterNumber}-10`,
      type: 'character',
      content: `E então? Gostou do que viu? 😘`,
    },
    {
      id: `msg-${chapterNumber}-11`,
      type: 'choice',
      choices: [
        { id: 'choice-7', text: 'Adorei!', nextMessageId: `msg-${chapterNumber}-12a` },
        { id: 'choice-8', text: 'Você é incrível', nextMessageId: `msg-${chapterNumber}-12b` },
        { id: 'choice-9', text: 'Quero ver mais', nextMessageId: `msg-${chapterNumber}-12c` },
      ]
    },
    {
      id: `msg-${chapterNumber}-12a`,
      type: 'character',
      content: `Fico tão feliz em saber disso... Continue voltando para ver mais. 💋`,
    },
    {
      id: `msg-${chapterNumber}-12b`,
      type: 'character',
      content: `Você também é especial... por isso escolhi você. ❤️`,
    },
    {
      id: `msg-${chapterNumber}-12c`,
      type: 'character',
      content: `Paciente... tudo no tempo certo. Continue nossa história e vou te surpreender cada vez mais. 😉`,
    },
  ];
  
  return messages;
};

// 10 Personagens completas
export const characters: Character[] = [
  {
    id: 'aiko',
    name: 'Aiko',
    style: 'Anime Colegial Elegante',
    personality: 'Tímida mas curiosa',
    sensuality: 'média',
    description: 'Uma estudante exemplar que esconde um lado ousado por trás da timidez.',
    lore: 'Aiko sempre foi a melhor aluna da turma, mas poucos sabem do seu lado secreto que ela revela apenas para pessoas especiais...',
    unlockCost: 80,
    chapters: [
      {
        id: 'aiko-ch1',
        number: 1,
        title: 'Primeiro Encontro',
        content: 'Aiko te convida para estudar na biblioteca...',
        imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 10 },
        chatMessages: createChatMessages('Aiko', 1),
      },
      {
        id: 'aiko-ch2',
        number: 2,
        title: 'Segredos Revelados',
        content: 'Ela compartilha seus pensamentos mais íntimos...',
        imageUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 15 },
        chatMessages: createChatMessages('Aiko', 2),
      },
      {
        id: 'aiko-ch3',
        number: 3,
        title: 'Depois da Aula',
        content: 'Um encontro especial após as aulas...',
        imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 20 },
        chatMessages: createChatMessages('Aiko', 3),
      },
      {
        id: 'aiko-ch4',
        number: 4,
        title: 'Confissões',
        content: 'Aiko revela seus verdadeiros sentimentos...',
        imageUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 25 },
        chatMessages: createChatMessages('Aiko', 4),
      },
      {
        id: 'aiko-ch5',
        number: 5,
        title: 'Momento Especial',
        content: 'Um momento íntimo e inesquecível...',
        imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=600&fit=crop',
        isFinal: true,
        reward: { coins: 30, gachaTicket: true },
        chatMessages: createChatMessages('Aiko', 5),
      },
    ],
    extraChapters: [
      {
        id: 'aiko-extra1',
        title: 'Festival de Verão',
        theme: 'Yukata no Festival',
        content: 'Aiko te convida para o festival de verão...',
        imageUrl: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=400&h=600&fit=crop',
        cost: 100,
        chatMessages: createChatMessages('Aiko', 99),
      },
    ],
  },
  {
    id: 'luna',
    name: 'Luna',
    style: 'Gótica Sofisticada',
    personality: 'Misteriosa e sedutora',
    sensuality: 'alta',
    description: 'Uma alma sombria com um charme irresistível que atrai como um ímã.',
    lore: 'Luna vive nas sombras da noite, mas quando ela te escolhe, você se torna parte do seu mundo obscuro e fascinante...',
    unlockCost: 120,
    chapters: [
      {
        id: 'luna-ch1',
        number: 1,
        title: 'Noite Sombria',
        content: 'Você encontra Luna em um clube noturno...',
        imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 10 },
        chatMessages: createChatMessages('Luna', 1),
      },
      {
        id: 'luna-ch2',
        number: 2,
        title: 'Convite Misterioso',
        content: 'Luna te leva para seu refúgio secreto...',
        imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 15 },
        chatMessages: createChatMessages('Luna', 2),
      },
      {
        id: 'luna-ch3',
        number: 3,
        title: 'Ritual Noturno',
        content: 'Uma cerimônia íntima sob a lua cheia...',
        imageUrl: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 20 },
        chatMessages: createChatMessages('Luna', 3),
      },
      {
        id: 'luna-ch4',
        number: 4,
        title: 'Segredos Obscuros',
        content: 'Luna revela seu passado misterioso...',
        imageUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 25 },
        chatMessages: createChatMessages('Luna', 4),
      },
      {
        id: 'luna-ch5',
        number: 5,
        title: 'Entrega Total',
        content: 'A noite mais intensa com Luna...',
        imageUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 30 },
        chatMessages: createChatMessages('Luna', 5),
      },
      {
        id: 'luna-ch6',
        number: 6,
        title: 'Eternidade Sombria',
        content: 'O vínculo eterno com Luna...',
        imageUrl: 'https://images.unsplash.com/photo-1479936343636-73cdc5aae0c3?w=400&h=600&fit=crop',
        isFinal: true,
        reward: { coins: 40, gachaTicket: true },
        chatMessages: createChatMessages('Luna', 6),
      },
    ],
    extraChapters: [
      {
        id: 'luna-extra1',
        title: 'Halloween Especial',
        theme: 'Noite das Bruxas',
        content: 'Luna te convida para uma festa especial...',
        imageUrl: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=400&h=600&fit=crop',
        cost: 120,
        chatMessages: createChatMessages('Luna', 99),
      },
    ],
  },
  {
    id: 'aria',
    name: 'Aria',
    style: 'Moderna e Sensual',
    personality: 'Confiante e provocante',
    sensuality: 'muito alta',
    description: 'Uma mulher moderna que sabe exatamente o que quer e como conseguir.',
    lore: 'Aria é uma influencer de sucesso que escolheu você entre milhares de seguidores. Prepare-se para uma experiência inesquecível...',
    unlockCost: 150,
    chapters: [
      {
        id: 'aria-ch1',
        number: 1,
        title: 'DM Especial',
        content: 'Aria te envia uma mensagem privada...',
        imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 10 },
        chatMessages: createChatMessages('Aria', 1),
      },
      {
        id: 'aria-ch2',
        number: 2,
        title: 'Encontro Secreto',
        content: 'Um encontro longe das câmeras...',
        imageUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 15 },
        chatMessages: createChatMessages('Aria', 2),
      },
      {
        id: 'aria-ch3',
        number: 3,
        title: 'Sessão Privada',
        content: 'Aria faz uma sessão de fotos só para você...',
        imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 20 },
        chatMessages: createChatMessages('Aria', 3),
      },
      {
        id: 'aria-ch4',
        number: 4,
        title: 'Viagem Especial',
        content: 'Um fim de semana inesquecível...',
        imageUrl: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 25 },
        chatMessages: createChatMessages('Aria', 4),
      },
      {
        id: 'aria-ch5',
        number: 5,
        title: 'Noite Inesquecível',
        content: 'A noite mais intensa com Aria...',
        imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 30 },
        chatMessages: createChatMessages('Aria', 5),
      },
      {
        id: 'aria-ch6',
        number: 6,
        title: 'Conexão Profunda',
        content: 'Aria revela seu lado mais íntimo...',
        imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 35 },
        chatMessages: createChatMessages('Aria', 6),
      },
      {
        id: 'aria-ch7',
        number: 7,
        title: 'Para Sempre',
        content: 'O compromisso final com Aria...',
        imageUrl: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=400&h=600&fit=crop',
        isFinal: true,
        reward: { coins: 50, gachaTicket: true },
        chatMessages: createChatMessages('Aria', 7),
      },
    ],
    extraChapters: [
      {
        id: 'aria-extra1',
        title: 'Praia Paradisíaca',
        theme: 'Verão Escaldante',
        content: 'Aria te leva para uma praia privada...',
        imageUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=600&fit=crop',
        cost: 150,
        chatMessages: createChatMessages('Aria', 99),
      },
    ],
  },
  {
    id: 'mei',
    name: 'Mei',
    style: 'Asiática Fofa e Provocante',
    personality: 'Doce mas atrevida',
    sensuality: 'média',
    description: 'Uma garota adorável que surpreende com sua ousadia quando menos se espera.',
    lore: 'Mei parece inocente à primeira vista, mas ela guarda surpresas picantes para quem ganha sua confiança...',
    unlockCost: 80,
    chapters: [
      {
        id: 'mei-ch1',
        number: 1,
        title: 'Café da Tarde',
        content: 'Mei te convida para um café especial...',
        imageUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 10 },
        chatMessages: createChatMessages('Mei', 1),
      },
      {
        id: 'mei-ch2',
        number: 2,
        title: 'Surpresa Doce',
        content: 'Mei prepara algo especial para você...',
        imageUrl: 'https://images.unsplash.com/photo-1479936343636-73cdc5aae0c3?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 15 },
        chatMessages: createChatMessages('Mei', 2),
      },
      {
        id: 'mei-ch3',
        number: 3,
        title: 'Lado Atrevido',
        content: 'Mei mostra seu lado mais ousado...',
        imageUrl: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 20 },
        chatMessages: createChatMessages('Mei', 3),
      },
      {
        id: 'mei-ch4',
        number: 4,
        title: 'Momento Íntimo',
        content: 'Um momento especial a sós...',
        imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 25 },
        chatMessages: createChatMessages('Mei', 4),
      },
      {
        id: 'mei-ch5',
        number: 5,
        title: 'Entrega Completa',
        content: 'Mei se entrega completamente...',
        imageUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=600&fit=crop',
        isFinal: true,
        reward: { coins: 30, gachaTicket: true },
        chatMessages: createChatMessages('Mei', 5),
      },
    ],
    extraChapters: [
      {
        id: 'mei-extra1',
        title: 'Cosplay Especial',
        theme: 'Fantasia Anime',
        content: 'Mei se veste especialmente para você...',
        imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=600&fit=crop',
        cost: 100,
        chatMessages: createChatMessages('Mei', 99),
      },
    ],
  },
  {
    id: 'nina',
    name: 'Nina',
    style: 'E-girl Vibrante',
    personality: 'Energética e divertida',
    sensuality: 'alta',
    description: 'Uma streamer carismática que traz energia e diversão para cada momento.',
    lore: 'Nina é a e-girl mais popular da plataforma, mas ela tem um lado especial que só mostra para você...',
    unlockCost: 120,
    chapters: [
      {
        id: 'nina-ch1',
        number: 1,
        title: 'Live Especial',
        content: 'Nina faz uma live privada só para você...',
        imageUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 10 },
        chatMessages: createChatMessages('Nina', 1),
      },
      {
        id: 'nina-ch2',
        number: 2,
        title: 'Offline',
        content: 'Um encontro fora das câmeras...',
        imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 15 },
        chatMessages: createChatMessages('Nina', 2),
      },
      {
        id: 'nina-ch3',
        number: 3,
        title: 'Jogando Junto',
        content: 'Uma noite de jogos e diversão...',
        imageUrl: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 20 },
        chatMessages: createChatMessages('Nina', 3),
      },
      {
        id: 'nina-ch4',
        number: 4,
        title: 'Conteúdo Exclusivo',
        content: 'Nina cria conteúdo especial para você...',
        imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 25 },
        chatMessages: createChatMessages('Nina', 4),
      },
      {
        id: 'nina-ch5',
        number: 5,
        title: 'Madrugada Especial',
        content: 'Uma madrugada inesquecível...',
        imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 30 },
        chatMessages: createChatMessages('Nina', 5),
      },
      {
        id: 'nina-ch6',
        number: 6,
        title: 'Conexão Real',
        content: 'Nina mostra quem ela realmente é...',
        imageUrl: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=400&h=600&fit=crop',
        isFinal: true,
        reward: { coins: 40, gachaTicket: true },
        chatMessages: createChatMessages('Nina', 6),
      },
    ],
    extraChapters: [
      {
        id: 'nina-extra1',
        title: 'Gaming Night',
        theme: 'Noite de Games',
        content: 'Uma noite épica de jogos...',
        imageUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=600&fit=crop',
        cost: 120,
        chatMessages: createChatMessages('Nina', 99),
      },
    ],
  },
  {
    id: 'sasha',
    name: 'Sasha',
    style: 'Cyberpunk Futurista',
    personality: 'Rebelde e intensa',
    sensuality: 'muito alta',
    description: 'Uma hacker rebelde do futuro com um magnetismo irresistível.',
    lore: 'Sasha vive nas sombras do mundo digital, mas quando ela te escolhe, você entra em uma realidade alternativa cheia de adrenalina...',
    unlockCost: 150,
    chapters: [
      {
        id: 'sasha-ch1',
        number: 1,
        title: 'Mensagem Criptografada',
        content: 'Sasha te envia uma mensagem secreta...',
        imageUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 10 },
        chatMessages: createChatMessages('Sasha', 1),
      },
      {
        id: 'sasha-ch2',
        number: 2,
        title: 'Encontro Clandestino',
        content: 'Um encontro em um lugar secreto...',
        imageUrl: 'https://images.unsplash.com/photo-1479936343636-73cdc5aae0c3?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 15 },
        chatMessages: createChatMessages('Sasha', 2),
      },
      {
        id: 'sasha-ch3',
        number: 3,
        title: 'Missão Perigosa',
        content: 'Sasha te leva em uma missão arriscada...',
        imageUrl: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 20 },
        chatMessages: createChatMessages('Sasha', 3),
      },
      {
        id: 'sasha-ch4',
        number: 4,
        title: 'Adrenalina Pura',
        content: 'Uma noite de pura adrenalina...',
        imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 25 },
        chatMessages: createChatMessages('Sasha', 4),
      },
      {
        id: 'sasha-ch5',
        number: 5,
        title: 'Conexão Neural',
        content: 'Uma experiência além da realidade...',
        imageUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 30 },
        chatMessages: createChatMessages('Sasha', 5),
      },
      {
        id: 'sasha-ch6',
        number: 6,
        title: 'Realidade Alternativa',
        content: 'Sasha te mostra um mundo novo...',
        imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 35 },
        chatMessages: createChatMessages('Sasha', 6),
      },
      {
        id: 'sasha-ch7',
        number: 7,
        title: 'Fusão Total',
        content: 'A conexão definitiva com Sasha...',
        imageUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400&h=600&fit=crop',
        isFinal: true,
        reward: { coins: 50, gachaTicket: true },
        chatMessages: createChatMessages('Sasha', 7),
      },
    ],
    extraChapters: [
      {
        id: 'sasha-extra1',
        title: 'Rave Neon',
        theme: 'Festa Cyberpunk',
        content: 'Uma festa futurista inesquecível...',
        imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=600&fit=crop',
        cost: 150,
        chatMessages: createChatMessages('Sasha', 99),
      },
    ],
  },
  {
    id: 'helena',
    name: 'Helena',
    style: 'Latina Moderna',
    personality: 'Apaixonada e envolvente',
    sensuality: 'alta',
    description: 'Uma latina de sangue quente que traz paixão para cada momento.',
    lore: 'Helena é dançarina profissional e quando ela se move, o mundo para. Prepare-se para ser envolvido por sua energia...',
    unlockCost: 120,
    chapters: [
      {
        id: 'helena-ch1',
        number: 1,
        title: 'Dança Sensual',
        content: 'Helena dança especialmente para você...',
        imageUrl: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 10 },
        chatMessages: createChatMessages('Helena', 1),
      },
      {
        id: 'helena-ch2',
        number: 2,
        title: 'Ritmo Quente',
        content: 'Uma noite de música e paixão...',
        imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 15 },
        chatMessages: createChatMessages('Helena', 2),
      },
      {
        id: 'helena-ch3',
        number: 3,
        title: 'Calor Latino',
        content: 'Helena mostra sua verdadeira paixão...',
        imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 20 },
        chatMessages: createChatMessages('Helena', 3),
      },
      {
        id: 'helena-ch4',
        number: 4,
        title: 'Noite de Fogo',
        content: 'Uma noite ardente com Helena...',
        imageUrl: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 25 },
        chatMessages: createChatMessages('Helena', 4),
      },
      {
        id: 'helena-ch5',
        number: 5,
        title: 'Paixão Intensa',
        content: 'A entrega total de Helena...',
        imageUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 30 },
        chatMessages: createChatMessages('Helena', 5),
      },
      {
        id: 'helena-ch6',
        number: 6,
        title: 'Amor Verdadeiro',
        content: 'Helena revela seu coração...',
        imageUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=600&fit=crop',
        isFinal: true,
        reward: { coins: 40, gachaTicket: true },
        chatMessages: createChatMessages('Helena', 6),
      },
    ],
    extraChapters: [
      {
        id: 'helena-extra1',
        title: 'Carnaval Especial',
        theme: 'Festa Brasileira',
        content: 'Helena te leva para o carnaval...',
        imageUrl: 'https://images.unsplash.com/photo-1479936343636-73cdc5aae0c3?w=400&h=600&fit=crop',
        cost: 120,
        chatMessages: createChatMessages('Helena', 99),
      },
    ],
  },
  {
    id: 'rin',
    name: 'Rin',
    style: 'Soft Realistic Romântica',
    personality: 'Delicada e carinhosa',
    sensuality: 'média',
    description: 'Uma alma gentil que traz romance e ternura para cada encontro.',
    lore: 'Rin é uma artista que vê beleza em tudo. Quando ela te escolhe como sua musa, você descobre um mundo de romance...',
    unlockCost: 80,
    chapters: [
      {
        id: 'rin-ch1',
        number: 1,
        title: 'Encontro no Parque',
        content: 'Rin te convida para um piquenique...',
        imageUrl: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 10 },
        chatMessages: createChatMessages('Rin', 1),
      },
      {
        id: 'rin-ch2',
        number: 2,
        title: 'Arte e Paixão',
        content: 'Rin pinta um retrato seu...',
        imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 15 },
        chatMessages: createChatMessages('Rin', 2),
      },
      {
        id: 'rin-ch3',
        number: 3,
        title: 'Momento Delicado',
        content: 'Um momento íntimo e romântico...',
        imageUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 20 },
        chatMessages: createChatMessages('Rin', 3),
      },
      {
        id: 'rin-ch4',
        number: 4,
        title: 'Confissão Sincera',
        content: 'Rin abre seu coração...',
        imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 25 },
        chatMessages: createChatMessages('Rin', 4),
      },
      {
        id: 'rin-ch5',
        number: 5,
        title: 'Amor Verdadeiro',
        content: 'A união perfeita com Rin...',
        imageUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400&h=600&fit=crop',
        isFinal: true,
        reward: { coins: 30, gachaTicket: true },
        chatMessages: createChatMessages('Rin', 5),
      },
    ],
    extraChapters: [
      {
        id: 'rin-extra1',
        title: 'Dia dos Namorados',
        theme: 'Romance Especial',
        content: 'Um dia especial com Rin...',
        imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=600&fit=crop',
        cost: 100,
        chatMessages: createChatMessages('Rin', 99),
      },
    ],
  },
  {
    id: 'valentina',
    name: 'Valentina',
    style: 'Modelo Fashion Europeia',
    personality: 'Sofisticada e elegante',
    sensuality: 'muito alta',
    description: 'Uma top model internacional com classe e sensualidade incomparáveis.',
    lore: 'Valentina desfilou nas maiores passarelas do mundo, mas agora ela quer desfilar só para você...',
    unlockCost: 150,
    chapters: [
      {
        id: 'valentina-ch1',
        number: 1,
        title: 'Desfile Privado',
        content: 'Valentina desfila exclusivamente para você...',
        imageUrl: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 10 },
        chatMessages: createChatMessages('Valentina', 1),
      },
      {
        id: 'valentina-ch2',
        number: 2,
        title: 'Sessão de Fotos',
        content: 'Uma sessão íntima de fotografia...',
        imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 15 },
        chatMessages: createChatMessages('Valentina', 2),
      },
      {
        id: 'valentina-ch3',
        number: 3,
        title: 'Viagem a Paris',
        content: 'Um fim de semana romântico em Paris...',
        imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 20 },
        chatMessages: createChatMessages('Valentina', 3),
      },
      {
        id: 'valentina-ch4',
        number: 4,
        title: 'Noite de Gala',
        content: 'Uma noite elegante e sofisticada...',
        imageUrl: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 25 },
        chatMessages: createChatMessages('Valentina', 4),
      },
      {
        id: 'valentina-ch5',
        number: 5,
        title: 'Luxo e Paixão',
        content: 'Uma noite de luxo e prazer...',
        imageUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 30 },
        chatMessages: createChatMessages('Valentina', 5),
      },
      {
        id: 'valentina-ch6',
        number: 6,
        title: 'Elegância Suprema',
        content: 'Valentina se entrega completamente...',
        imageUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 35 },
        chatMessages: createChatMessages('Valentina', 6),
      },
      {
        id: 'valentina-ch7',
        number: 7,
        title: 'Amor Eterno',
        content: 'O compromisso final com Valentina...',
        imageUrl: 'https://images.unsplash.com/photo-1479936343636-73cdc5aae0c3?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 40 },
        chatMessages: createChatMessages('Valentina', 7),
      },
      {
        id: 'valentina-ch8',
        number: 8,
        title: 'Perfeição Absoluta',
        content: 'A união perfeita com Valentina...',
        imageUrl: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=400&h=600&fit=crop',
        isFinal: true,
        reward: { coins: 50, gachaTicket: true },
        chatMessages: createChatMessages('Valentina', 8),
      },
    ],
    extraChapters: [
      {
        id: 'valentina-extra1',
        title: 'Fashion Week',
        theme: 'Semana de Moda',
        content: 'Valentina te leva para a Fashion Week...',
        imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=600&fit=crop',
        cost: 150,
        chatMessages: createChatMessages('Valentina', 99),
      },
    ],
  },
  {
    id: 'yuki',
    name: 'Yuki',
    style: 'Clean Aesthetic Angelical',
    personality: 'Pura e encantadora',
    sensuality: 'média',
    description: 'Uma beleza angelical que traz paz e encantamento para cada momento.',
    lore: 'Yuki parece um anjo caído do céu. Sua pureza esconde uma sensualidade delicada que só se revela para os escolhidos...',
    unlockCost: 80,
    chapters: [
      {
        id: 'yuki-ch1',
        number: 1,
        title: 'Encontro Celestial',
        content: 'Yuki aparece como um anjo...',
        imageUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 10 },
        chatMessages: createChatMessages('Yuki', 1),
      },
      {
        id: 'yuki-ch2',
        number: 2,
        title: 'Pureza Revelada',
        content: 'Yuki mostra sua verdadeira essência...',
        imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 15 },
        chatMessages: createChatMessages('Yuki', 2),
      },
      {
        id: 'yuki-ch3',
        number: 3,
        title: 'Delicadeza Suprema',
        content: 'Um momento de pura delicadeza...',
        imageUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 20 },
        chatMessages: createChatMessages('Yuki', 3),
      },
      {
        id: 'yuki-ch4',
        number: 4,
        title: 'Toque Angelical',
        content: 'Yuki te toca com ternura...',
        imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=600&fit=crop',
        isFinal: false,
        reward: { coins: 25 },
        chatMessages: createChatMessages('Yuki', 4),
      },
      {
        id: 'yuki-ch5',
        number: 5,
        title: 'Paraíso Encontrado',
        content: 'A união celestial com Yuki...',
        imageUrl: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=400&h=600&fit=crop',
        isFinal: true,
        reward: { coins: 30, gachaTicket: true },
        chatMessages: createChatMessages('Yuki', 5),
      },
    ],
    extraChapters: [
      {
        id: 'yuki-extra1',
        title: 'Natal Angelical',
        theme: 'Magia de Natal',
        content: 'Um Natal mágico com Yuki...',
        imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=600&fit=crop',
        cost: 100,
        chatMessages: createChatMessages('Yuki', 99),
      },
    ],
  },
];

// 40 Gacha Cards (4 por personagem)
export const gachaCards: GachaCard[] = characters.flatMap(char => [
  {
    id: `${char.id}-gacha-1`,
    characterId: char.id,
    characterName: char.name,
    imageUrl: char.chapters[0]?.imageUrl || 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=600&fit=crop',
    rarity: 'comum',
  },
  {
    id: `${char.id}-gacha-2`,
    characterId: char.id,
    characterName: char.name,
    imageUrl: char.chapters[1]?.imageUrl || 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=600&fit=crop',
    rarity: 'raro',
  },
  {
    id: `${char.id}-gacha-3`,
    characterId: char.id,
    characterName: char.name,
    imageUrl: char.chapters[2]?.imageUrl || 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=600&fit=crop',
    rarity: 'épico',
  },
  {
    id: `${char.id}-gacha-4`,
    characterId: char.id,
    characterName: char.name,
    imageUrl: char.chapters[char.chapters.length - 1]?.imageUrl || 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400&h=600&fit=crop',
    rarity: 'lendário',
  },
]);

// Pacotes da loja
export const shopPackages: ShopPackage[] = [
  { id: 'pack-1', coins: 100, price: 'R$ 4,90' },
  { id: 'pack-2', coins: 250, price: 'R$ 9,90' },
  { id: 'pack-3', coins: 700, price: 'R$ 19,90' },
  { id: 'pack-4', coins: 1600, price: 'R$ 39,90' },
  { id: 'pack-5', coins: 5000, price: 'R$ 99,90' },
];
